apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these are replica set labels
  labels:
    purpose: toleration-demo
    project: roboshop
spec:
  replicas: 3
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: toleration-demo
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        purpose: toleration-demo
        project: roboshop
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-19-222.ec2.internal
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshop"
        effect: "NoSchedule"