apiVersion: v1
kind: Pod

metadata:
  name: node-affinity

spec:
  affinity:
    nodeAffinity:

      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1f

      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop

      - weight: 50
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - Amazon

  containers:
  - name: nginx
    image: nginx